const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const ctx={};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../scripts/shared-profile.js'),'utf8'),ctx);
const out=ctx.main({proxies:[{name:'test-hy',type:'hysteria2',server:'edge.example.com',password:'TEST_ONLY'}]});
const regexRule=out.rules.find(r=>r.startsWith('DOMAIN-REGEX,'));
const regex=new RegExp(regexRule.split(',')[1]);
assert(regex.test('upos-test.akamaized.net'));
assert(!regex.test('upos-testXakamaizedYnet'));
assert(!regex.test('upos-test.akamaized.net.attacker.example'));
for(const name of ['上网线路','自动切换（推荐）','DIRECT']) assert.throws(()=>ctx.main({proxies:[{name,type:'hysteria2',server:'edge.example.com'}]}));
const auto=out['proxy-groups'][1];assert.equal(auto.interval,15);assert.equal(auto.timeout,5000);
console.log('PASS: regex positive/negative samples, reserved names, health settings; no network or live config loaded');

for (const d of ['gov.cn','sogou.com','so.com','miguvideo.com','douban.com','bilivideo.com']) assert(out.rules.includes(`DOMAIN-SUFFIX,${d},DIRECT`));
assert(out.rules.indexOf('GEOSITE,cn,DIRECT') < out.rules.indexOf('GEOIP,CN,DIRECT'));
assert(out.dns['direct-nameserver'].every(x=>x.endsWith('#DIRECT')));
const extra={proxies:[{name:'hy',type:'hysteria2',server:'edge.example.com'}], 'proxy-providers':{'japan-primary':{type:'file',path:'./test-only.yaml'}}};
const result=ctx.main(extra);
assert.equal(result['proxy-groups'][1].proxies.at(-1),'日本低延迟（跨订阅）');
assert.deepEqual(Array.from(result['proxy-groups'][2].use),['japan-primary']);
assert.equal(result['proxy-groups'][2]['empty-fallback'],'REJECT');
assert.match(result['proxy-groups'][2].filter,/日本/);
assert.equal(JSON.stringify(ctx.main(JSON.parse(JSON.stringify(result)))),JSON.stringify(result));
assert.throws(()=>ctx.main({proxies:[{name:'日本低延迟（跨订阅）',type:'hysteria2',server:'edge.example.com'}]}));
console.log('PASS: optional Japan providers, reserved group, idempotence, domestic category routing and direct DNS');
