const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx={};vm.runInNewContext(fs.readFileSync(__dirname+'/扩展脚本-v16-面板简化-20260920.js','utf8')+'\nfunction main(config) {return config;}',ctx);
const input={proxies:[{name:'hy',type:'hysteria2'},{name:'cdn',type:'vless',network:'ws'},{name:'tls',type:'vless',network:'tcp',server:'example.com'}],'proxy-providers':{'日本备用-新':{}},'proxy-groups':[{name:'PROXY',type:'select',proxies:['hy']}],rules:['DOMAIN,test.example,AUTO-STABLE','MATCH,PROXY']};
const c=ctx.main(input),gs=c['proxy-groups'];assert.deepEqual(gs.filter(g=>!g.hidden).map(g=>g.name),['上网方式','切换到手动节点（展开选择）']);
assert.equal(JSON.stringify(gs[0].proxies),JSON.stringify(['自动上网（推荐）','日本上网（自动测速）','切换到手动节点（展开选择）','直连上网（不经代理）']));
const auto=gs.find(g=>g.type==='fallback');assert.equal(JSON.stringify(auto.proxies),JSON.stringify(['hy','cdn','tls','日本上网（自动测速）']));assert.equal(auto.lazy,false);assert.equal(auto.interval,15);
assert.ok(c.rules.includes('GEOSITE,cn,DIRECT'));assert.ok(c.rules.includes('DOMAIN,test.example,自动上网（推荐）'));
assert.equal(gs.find(g=>g.name==='直连上网（不经代理）').proxies[0],'DIRECT');
const snapshot=JSON.stringify(c);assert.equal(JSON.stringify(ctx.main(c)),snapshot);
const noJp=ctx.main({proxies:[{name:'hy',type:'hysteria2'}],'proxy-groups':[{name:'PROXY',type:'select',proxies:['hy']}],rules:['MATCH,PROXY']});assert.equal(noJp['proxy-groups'][0].proxies.length,3);
console.log('PASS: purpose entry, four choices including manual nodes, fallback order, hidden active checks, direct mode, rule aliases, idempotence and no-provider case');
